### ISSUE TITLE
unresolved reference:exposed.....

### ISSUE THREAD

**Issue by WenCheese** [raharrison/kotlin-ktor-exposed-starter#1]
import org.jetbrains.exposed.sql.Table
unresolved reference:exposed.....
i have compile exposed successful like this:    compile "org.jetbrains.exposed:exposed:0.10.4"

**Comment by raharrison** [comment]
Are you sure the dependency is being brought into your project correctly? Sounds like your project might not be set up correctly.

This starter is working as is with 2018.2

**Comment by WenCheese** [comment]
Sorry i checked my project and i found that i missed this: 
maven { url = "https://dl.bintray.com/kotlin/exposed"}

now my project worked well.thanks.
