### ISSUE TITLE
netty -> CIO

### ISSUE THREAD

**Issue by akurdyukov** [raharrison/kotlin-ktor-exposed-starter#17]
Recent Kotlin versions have Coroutine IO (CIO) library. Do you think it's reasonable to migrate netty to CIO for this starter?

**Comment by raharrison** [comment]
I believe the CIO implementation is still very much under development and a focus area according to the Ktor roadmap. The Netty engine seems to be most stable (at least from my experience), which is important for a starter.

Am happy to change it sometime in the future though.

**Comment by akurdyukov** [comment]
I definitely agree that netty is the most stable engine. But I haven't found any public roadmap for ktor or CIO. I'll ask ktor team for the status.

**Comment by raharrison** [comment]
They have a general one at [https://blog.jetbrains.com/ktor/2020/08/10/ktor-roadmap-for-2020-2021/](https://blog.jetbrains.com/ktor/2020/08/10/ktor-roadmap-for-2020-2021/) but I think I heard something about focus on CIO from one of their conference talks recently.

**Comment by raharrison** [comment]
Netty is still the default engine recommended by the Ktor folk so closing this for now.
