### ISSUE TITLE
Version control for database

### ISSUE THREAD

**Issue by viartemev** [raharrison/kotlin-ktor-exposed-starter#5]
Would you mind to add support of Flyway or Liquibase?

**Comment by AdityaAnand1** [comment]
👍 Yes, that'd be an excellent addition @raharrison

**Comment by viartemev** [comment]
@AdityaAnand1 I have ktor flyway plugin for it: https://github.com/viartemev/ktor-flyway-feature

**Comment by akurdyukov** [comment]
PR for the issue: https://github.com/raharrison/kotlin-ktor-exposed-starter/pull/19

**Comment by raharrison** [comment]
Merged #19
